import { readFile } from 'node:fs/promises';
import { request } from 'node:https';
import { homedir } from 'node:os';

const projectId = process.argv[2] ?? 'ezq-dev-cubiquitous';
const configPath = `${homedir()}/.config/configstore/firebase-tools.json`;
const firebaseToolsConfig = JSON.parse(await readFile(configPath, 'utf8'));
const accessToken = firebaseToolsConfig.tokens?.access_token;

if (!accessToken) {
  throw new Error('No Firebase CLI access token found. Run firebase login first.');
}

const businessDate = new Intl.DateTimeFormat('en-CA', {
  timeZone: 'Asia/Kolkata',
  year: 'numeric',
  month: '2-digit',
  day: '2-digit',
}).format(new Date());
const now = Date.now();
const minutesAgo = (minutes) => new Date(now - minutes * 60 * 1000).toISOString();

const documents = {
  'restaurants/the-spice-house': {
    name: 'The Spice House',
    cuisine: 'Modern Indian',
    city: 'Bengaluru',
    isActive: true,
    createdAt: new Date().toISOString(),
  },
  'restaurants/the-spice-house/branches/indiranagar': {
    name: 'Indiranagar',
    area: 'Indiranagar',
    address: '100 Feet Road, Indiranagar, Bengaluru',
    menuPdfUrl: '/demo-menu.pdf',
    menuPreviewImageUrl: '/demo-menu-page-1.png',
    isActive: true,
    averageTurnoverMinutes: 35,
    createdAt: new Date().toISOString(),
  },
  'restaurants/the-spice-house/branches/indiranagar/tables/t1': {
    tableNumber: 'T1',
    capacity: 2,
    tableType: '2-top',
    section: 'main',
    status: 'occupied',
    currentQueueEntryId: 'q15',
    currentTokenCode: 'Q15',
    currentCycleStartAt: minutesAgo(18),
    currentCycleSource: 'previous_completion',
    occupiedAt: minutesAgo(14),
    sortOrder: 1,
  },
  'restaurants/the-spice-house/branches/indiranagar/tables/t2': {
    tableNumber: 'T2',
    capacity: 4,
    tableType: '4-top',
    section: 'main',
    status: 'occupied',
    currentQueueEntryId: 'q18',
    currentTokenCode: 'Q18',
    currentCycleStartAt: minutesAgo(3),
    currentCycleSource: 'previous_completion',
    reservedAt: minutesAgo(3),
    occupiedAt: minutesAgo(3),
    sortOrder: 2,
  },
  'restaurants/the-spice-house/branches/indiranagar/tables/t3': {
    tableNumber: 'T3',
    capacity: 4,
    tableType: '4-top',
    section: 'patio',
    status: 'available',
    lastCompletedQueueEntryId: 'q14',
    lastCompletedPartySize: 4,
    lastCompletedAt: minutesAgo(32),
    lastCycleStartAt: minutesAgo(76),
    lastCycleEndAt: minutesAgo(32),
    sortOrder: 3,
  },
  'restaurants/the-spice-house/branches/indiranagar/tables/t4': {
    tableNumber: 'T4',
    capacity: 6,
    tableType: '6-top',
    section: 'family',
    status: 'available',
    cleaningStartedAt: null,
    sortOrder: 4,
  },
  [`restaurants/the-spice-house/branches/indiranagar/dailyCounters/${businessDate}`]: {
    businessDate,
    lastTokenNumber: 35,
    totalJoined: 35,
    totalSeated: 17,
    totalSkipped: 1,
    totalCancelled: 2,
    totalNoShow: 1,
    peakQueueDepth: 14,
    updatedAt: new Date(now).toISOString(),
  },
  'restaurants/the-spice-house/branches/indiranagar/queueEntries/q15': {
    tokenNumber: 15,
    tokenCode: 'Q15',
    businessDate,
    customerName: 'Meera Iyer',
    phone: '+919876543210',
    partySize: 2,
    partySizeBand: '1-2',
    notes: 'Window seat if possible',
    customerId: null,
    sessionType: 'web_guest',
    appSource: 'web',
    status: 'seated',
    assignedTableId: 't1',
    assignedTableNumber: 'T1',
    estimatedWaitMinutes: 0,
    queuePosition: 0,
    extensionUsed: false,
    joinedAt: minutesAgo(46),
    reservedAt: minutesAgo(18),
    seatedAt: minutesAgo(14),
    tableCycleStartAt: minutesAgo(18),
    tableCycleSource: 'previous_completion',
    updatedAt: minutesAgo(14),
  },
  'restaurants/the-spice-house/branches/indiranagar/queueEntries/q18': {
    tokenNumber: 18,
    tokenCode: 'Q18',
    businessDate,
    customerName: 'Arjun Nair',
    phone: '+919812345678',
    partySize: 4,
    partySizeBand: '3-4',
    notes: 'Birthday dinner',
    customerId: null,
    sessionType: 'web_guest',
    appSource: 'web',
    status: 'seated',
    assignedTableId: 't2',
    assignedTableNumber: 'T2',
    estimatedWaitMinutes: 0,
    queuePosition: 0,
    extensionUsed: false,
    joinedAt: minutesAgo(24),
    reservedAt: minutesAgo(3),
    seatedAt: minutesAgo(3),
    tableCycleStartAt: minutesAgo(3),
    tableCycleSource: 'previous_completion',
    updatedAt: minutesAgo(3),
  },
  'restaurants/the-spice-house/branches/indiranagar/queueEntries/q19': {
    tokenNumber: 19,
    tokenCode: 'Q19',
    businessDate,
    customerName: 'Nisha Rao',
    phone: '+919900112233',
    partySize: 3,
    partySizeBand: '3-4',
    notes: 'Needs high chair',
    customerId: null,
    sessionType: 'web_guest',
    appSource: 'web',
    status: 'on_the_way',
    assignedTableId: null,
    assignedTableNumber: null,
    estimatedWaitMinutes: 10,
    queuePosition: 2,
    extensionUsed: true,
    joinedAt: minutesAgo(17),
    onTheWayAt: minutesAgo(4),
    updatedAt: minutesAgo(4),
  },
  'restaurants/the-spice-house/branches/indiranagar/queueEntries/q20': {
    tokenNumber: 20,
    tokenCode: 'Q20',
    businessDate,
    customerName: 'Kabir Shah',
    phone: '+919700889900',
    partySize: 6,
    partySizeBand: '5-6',
    notes: 'Prefers family section',
    customerId: null,
    sessionType: 'web_guest',
    appSource: 'web',
    status: 'waiting',
    assignedTableId: null,
    assignedTableNumber: null,
    estimatedWaitMinutes: 15,
    queuePosition: 3,
    extensionUsed: false,
    joinedAt: minutesAgo(11),
    updatedAt: minutesAgo(11),
  },
  'restaurants/the-spice-house/branches/indiranagar/queueEntries/q21': {
    tokenNumber: 21,
    tokenCode: 'Q21',
    businessDate,
    customerName: 'Priya Menon',
    phone: '+919611223344',
    partySize: 2,
    partySizeBand: '1-2',
    notes: null,
    customerId: null,
    sessionType: 'web_guest',
    appSource: 'web',
    status: 'waiting',
    assignedTableId: null,
    assignedTableNumber: null,
    estimatedWaitMinutes: 20,
    queuePosition: 4,
    extensionUsed: false,
    joinedAt: minutesAgo(6),
    updatedAt: minutesAgo(6),
  },
};

const extraTables = [
  {
    id: 't5',
    tableNumber: 'T5',
    capacity: 2,
    tableType: '2-top',
    section: 'bar',
    status: 'occupied',
    currentQueueEntryId: 'q22',
    currentTokenCode: 'Q22',
    currentCycleStartAt: minutesAgo(21),
    currentCycleSource: 'previous_completion',
    occupiedAt: minutesAgo(17),
    sortOrder: 5,
  },
  {
    id: 't6',
    tableNumber: 'T6',
    capacity: 2,
    tableType: '2-top',
    section: 'window',
    status: 'occupied',
    currentQueueEntryId: 'q23',
    currentTokenCode: 'Q23',
    currentCycleStartAt: minutesAgo(5),
    currentCycleSource: 'previous_completion',
    reservedAt: minutesAgo(5),
    occupiedAt: minutesAgo(5),
    sortOrder: 6,
  },
  {
    id: 't7',
    tableNumber: 'T7',
    capacity: 2,
    tableType: '2-top',
    section: 'patio',
    status: 'available',
    lastCompletedQueueEntryId: 'q12',
    lastCompletedPartySize: 2,
    lastCompletedAt: minutesAgo(19),
    lastCycleStartAt: minutesAgo(57),
    lastCycleEndAt: minutesAgo(19),
    sortOrder: 7,
  },
  {
    id: 't8',
    tableNumber: 'T8',
    capacity: 4,
    tableType: '4-top',
    section: 'main',
    status: 'available',
    sortOrder: 8,
  },
  {
    id: 't9',
    tableNumber: 'T9',
    capacity: 4,
    tableType: '4-top',
    section: 'patio',
    status: 'available',
    sortOrder: 9,
  },
  {
    id: 't10',
    tableNumber: 'T10',
    capacity: 4,
    tableType: '4-top',
    section: 'main',
    status: 'occupied',
    currentQueueEntryId: 'q24',
    currentTokenCode: 'Q24',
    currentCycleStartAt: minutesAgo(29),
    currentCycleSource: 'first_reservation',
    occupiedAt: minutesAgo(25),
    sortOrder: 10,
  },
  {
    id: 't11',
    tableNumber: 'T11',
    capacity: 6,
    tableType: '6-top',
    section: 'family',
    status: 'available',
    sortOrder: 11,
  },
  {
    id: 't12',
    tableNumber: 'T12',
    capacity: 6,
    tableType: '6-top',
    section: 'family',
    status: 'occupied',
    currentQueueEntryId: 'q25',
    currentTokenCode: 'Q25',
    currentCycleStartAt: minutesAgo(2),
    currentCycleSource: 'previous_completion',
    reservedAt: minutesAgo(2),
    occupiedAt: minutesAgo(2),
    sortOrder: 12,
  },
  {
    id: 't13',
    tableNumber: 'T13',
    capacity: 8,
    tableType: '8-top',
    section: 'private',
    status: 'available',
    sortOrder: 13,
  },
  {
    id: 't14',
    tableNumber: 'T14',
    capacity: 10,
    tableType: '10-top',
    section: 'private',
    status: 'available',
    sortOrder: 14,
  },
];

const extraQueueEntries = [
  {
    id: 'q22',
    tokenNumber: 22,
    tokenCode: 'Q22',
    customerName: 'Rohan Kapoor',
    phone: '+919845551122',
    partySize: 2,
    partySizeBand: '1-2',
    notes: 'Quick lunch',
    status: 'seated',
    assignedTableId: 't5',
    assignedTableNumber: 'T5',
    estimatedWaitMinutes: 0,
    queuePosition: 0,
    joinedAt: minutesAgo(38),
    reservedAt: minutesAgo(21),
    seatedAt: minutesAgo(17),
    tableCycleStartAt: minutesAgo(21),
    tableCycleSource: 'previous_completion',
    updatedAt: minutesAgo(17),
  },
  {
    id: 'q23',
    tokenNumber: 23,
    tokenCode: 'Q23',
    customerName: 'Sara D Souza',
    phone: '+919845551133',
    partySize: 2,
    partySizeBand: '1-2',
    notes: 'Anniversary',
    status: 'seated',
    assignedTableId: 't6',
    assignedTableNumber: 'T6',
    estimatedWaitMinutes: 0,
    queuePosition: 0,
    joinedAt: minutesAgo(28),
    reservedAt: minutesAgo(5),
    seatedAt: minutesAgo(5),
    tableCycleStartAt: minutesAgo(5),
    tableCycleSource: 'previous_completion',
    updatedAt: minutesAgo(5),
  },
  {
    id: 'q24',
    tokenNumber: 24,
    tokenCode: 'Q24',
    customerName: 'Devika Pillai',
    phone: '+919845551144',
    partySize: 4,
    partySizeBand: '3-4',
    notes: 'Near charging point',
    status: 'seated',
    assignedTableId: 't10',
    assignedTableNumber: 'T10',
    estimatedWaitMinutes: 0,
    queuePosition: 0,
    joinedAt: minutesAgo(44),
    reservedAt: minutesAgo(29),
    seatedAt: minutesAgo(25),
    tableCycleStartAt: minutesAgo(29),
    tableCycleSource: 'first_reservation',
    updatedAt: minutesAgo(25),
  },
  {
    id: 'q25',
    tokenNumber: 25,
    tokenCode: 'Q25',
    customerName: 'Manav Bhat',
    phone: '+919845551155',
    partySize: 6,
    partySizeBand: '5-6',
    notes: 'Kids menu',
    status: 'seated',
    assignedTableId: 't12',
    assignedTableNumber: 'T12',
    estimatedWaitMinutes: 0,
    queuePosition: 0,
    joinedAt: minutesAgo(22),
    reservedAt: minutesAgo(2),
    seatedAt: minutesAgo(2),
    tableCycleStartAt: minutesAgo(2),
    tableCycleSource: 'previous_completion',
    updatedAt: minutesAgo(2),
  },
  {
    id: 'q26',
    tokenNumber: 26,
    tokenCode: 'Q26',
    customerName: 'Aisha Khan',
    phone: '+919845551166',
    partySize: 1,
    partySizeBand: '1-2',
    notes: null,
    status: 'waiting',
    estimatedWaitMinutes: 10,
    queuePosition: 3,
    joinedAt: minutesAgo(18),
    updatedAt: minutesAgo(18),
  },
  {
    id: 'q27',
    tokenNumber: 27,
    tokenCode: 'Q27',
    customerName: 'Karthik S',
    phone: '+919845551177',
    partySize: 2,
    partySizeBand: '1-2',
    notes: 'Patio preferred',
    status: 'waiting',
    estimatedWaitMinutes: 15,
    queuePosition: 4,
    joinedAt: minutesAgo(15),
    updatedAt: minutesAgo(15),
  },
  {
    id: 'q28',
    tokenNumber: 28,
    tokenCode: 'Q28',
    customerName: 'Leela Raman',
    phone: '+919845551188',
    partySize: 3,
    partySizeBand: '3-4',
    notes: null,
    status: 'on_the_way',
    estimatedWaitMinutes: 15,
    queuePosition: 5,
    extensionUsed: true,
    joinedAt: minutesAgo(14),
    onTheWayAt: minutesAgo(3),
    updatedAt: minutesAgo(3),
  },
  {
    id: 'q29',
    tokenNumber: 29,
    tokenCode: 'Q29',
    customerName: 'Vikram Jain',
    phone: '+919845551199',
    partySize: 4,
    partySizeBand: '3-4',
    notes: 'No onion',
    status: 'waiting',
    estimatedWaitMinutes: 20,
    queuePosition: 6,
    joinedAt: minutesAgo(12),
    updatedAt: minutesAgo(12),
  },
  {
    id: 'q30',
    tokenNumber: 30,
    tokenCode: 'Q30',
    customerName: 'Tara Bose',
    phone: '+919845551200',
    partySize: 5,
    partySizeBand: '5-6',
    notes: 'One wheelchair access',
    status: 'waiting',
    estimatedWaitMinutes: 25,
    queuePosition: 7,
    joinedAt: minutesAgo(10),
    updatedAt: minutesAgo(10),
  },
  {
    id: 'q31',
    tokenNumber: 31,
    tokenCode: 'Q31',
    customerName: 'Neil Abraham',
    phone: '+919845551211',
    partySize: 6,
    partySizeBand: '5-6',
    notes: null,
    status: 'waiting',
    estimatedWaitMinutes: 30,
    queuePosition: 8,
    joinedAt: minutesAgo(8),
    updatedAt: minutesAgo(8),
  },
  {
    id: 'q32',
    tokenNumber: 32,
    tokenCode: 'Q32',
    customerName: 'Gayatri Rao',
    phone: '+919845551222',
    partySize: 7,
    partySizeBand: '7+',
    notes: 'Celebration cake',
    status: 'waiting',
    estimatedWaitMinutes: 35,
    queuePosition: 9,
    joinedAt: minutesAgo(7),
    updatedAt: minutesAgo(7),
  },
  {
    id: 'q33',
    tokenNumber: 33,
    tokenCode: 'Q33',
    customerName: 'Omar Farooq',
    phone: '+919845551233',
    partySize: 8,
    partySizeBand: '7+',
    notes: 'Private room if free',
    status: 'waiting',
    estimatedWaitMinutes: 40,
    queuePosition: 10,
    joinedAt: minutesAgo(5),
    updatedAt: minutesAgo(5),
  },
  {
    id: 'q34',
    tokenNumber: 34,
    tokenCode: 'Q34',
    customerName: 'Ishaan Mehta',
    phone: '+919845551244',
    partySize: 10,
    partySizeBand: '7+',
    notes: 'Corporate group',
    status: 'waiting',
    estimatedWaitMinutes: 45,
    queuePosition: 11,
    joinedAt: minutesAgo(3),
    updatedAt: minutesAgo(3),
  },
  {
    id: 'q35',
    tokenNumber: 35,
    tokenCode: 'Q35',
    customerName: 'Ananya Sen',
    phone: '+919845551255',
    partySize: 12,
    partySizeBand: '7+',
    notes: 'May split into two tables',
    status: 'waiting',
    estimatedWaitMinutes: 50,
    queuePosition: 12,
    joinedAt: minutesAgo(1),
    updatedAt: minutesAgo(1),
  },
];

for (const table of extraTables) {
  const { id, ...data } = table;
  documents[`restaurants/the-spice-house/branches/indiranagar/tables/${id}`] =
    data;
}

for (const entry of extraQueueEntries) {
  const { id, ...data } = entry;
  documents[
    `restaurants/the-spice-house/branches/indiranagar/queueEntries/${id}`
  ] = {
    businessDate,
    customerId: null,
    sessionType: 'web_guest',
    appSource: 'web',
    assignedTableId: null,
    assignedTableNumber: null,
    extensionUsed: false,
    ...data,
  };
}

function firestoreValue(value) {
  if (value === null || value === undefined) return { nullValue: null };
  if (typeof value === 'boolean') return { booleanValue: value };
  if (Number.isInteger(value)) return { integerValue: String(value) };
  if (typeof value === 'number') return { doubleValue: value };
  return { stringValue: String(value) };
}

function firestoreDocument(data) {
  return {
    fields: Object.fromEntries(
      Object.entries(data).map(([key, value]) => [key, firestoreValue(value)]),
    ),
  };
}

function patchDocument(path, data) {
  const body = JSON.stringify(firestoreDocument(data));
  const requestPath = `/v1/projects/${projectId}/databases/(default)/documents/${path}`;

  return new Promise((resolve, reject) => {
    const req = request(
      {
        method: 'PATCH',
        hostname: 'firestore.googleapis.com',
        path: requestPath,
        headers: {
          Authorization: `Bearer ${accessToken}`,
          'Content-Type': 'application/json',
          'Content-Length': Buffer.byteLength(body),
        },
      },
      (res) => {
        let responseBody = '';
        res.on('data', (chunk) => {
          responseBody += chunk;
        });
        res.on('end', () => {
          if (res.statusCode >= 200 && res.statusCode < 300) {
            resolve();
            return;
          }
          reject(
            new Error(
              `Failed to seed ${path}: ${res.statusCode} ${responseBody}`,
            ),
          );
        });
      },
    );
    req.on('error', reject);
    req.end(body);
  });
}

for (const [path, data] of Object.entries(documents)) {
  await patchDocument(path, data);
  console.log(`Seeded ${path}`);
}

console.log(`Seeded demo Firestore data in ${projectId}`);
